In [1]:
import pandas as pd

# Data sampah dari tabel dalam bentuk dictionary
data_sampah = {
    'Kabupaten/Kota': [
        "Kota Bandung", "Kota Bekasi", "Kota Bogor", "Kota Depok", "Kota Cimahi", 
        "Kabupaten Bandung", "Kabupaten Bekasi", "Kabupaten Bogor", "Kabupaten Cirebon", "Kabupaten Garut",
        "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka",
        "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi",
        "Kabupaten Sumedang", "Kabupaten Tasikmalaya"
    ],
    'Produksi Sampah 2020 (ton)': [
        280000, 500000, 240000, 210000, 120000, 350000, 410000, 370000, 220000, 260000, 
        300000, 450000, 200000, 190000, 140000, 230000, 250000, 310000, 180000, 270000
    ],
    'Produksi Sampah 2021 (ton)': [
        290000, 510000, 250000, 220000, 125000, 355000, 415000, 375000, 225000, 265000, 
        305000, 455000, 205000, 195000, 145000, 235000, 255000, 315000, 185000, 275000
    ],
    'Produksi Sampah 2022 (ton)': [
        300000, 520000, 260000, 230000, 130000, 360000, 420000, 380000, 230000, 270000, 
        310000, 460000, 210000, 200000, 150000, 240000, 260000, 320000, 190000, 280000
    ]
}


df_sampah = pd.DataFrame(data_sampah)
df_sampah['Rata-rata Produksi Sampah'] = df_sampah[['Produksi Sampah 2020 (ton)', 'Produksi Sampah 2021 (ton)', 'Produksi Sampah 2022 (ton)']].mean(axis=1)

df_sampah

,Kabupaten/Kota,Produksi Sampah 2020 (ton),Produksi Sampah 2021 (ton),Produksi Sampah 2022 (ton),Rata-rata Produksi Sampah
0,Kota Bandung,280000,290000,300000,290000.0
1,Kota Bekasi,500000,510000,520000,510000.0
2,Kota Bogor,240000,250000,260000,250000.0
3,Kota Depok,210000,220000,230000,220000.0
4,Kota Cimahi,120000,125000,130000,125000.0
5,Kabupaten Bandung,350000,355000,360000,355000.0
6,Kabupaten Bekasi,410000,415000,420000,415000.0
7,Kabupaten Bogor,370000,375000,380000,375000.0
8,Kabupaten Cirebon,220000,225000,230000,225000.0
9,Kabupaten Garut,260000,265000,270000,265000.0
10,Kabupaten Indramayu,300000,305000,310000,305000.0
11,Kabupaten Karawang,450000,455000,460000,455000.0
12,Kabupaten Kuningan,200000,205000,210000,205000.0
13,Kabupaten Majalengka,190000,195000,200000,195000.0
14,Kabupaten Pangandaran,140000,145000,150000,145000.0
15,Kabupaten Purwakarta,230000,235000,240000,235000.0
16,Kabupaten Subang,250000,255000,260000,255000.0
17,Kabupaten Sukabumi,310000,315000,320000,315000.0
18,Kabupaten Sumedang,180000,185000,190000,185000.0
19,Kabupaten Tasikmalaya,270000,275000,280000,275000.0